# Generated by Django 6.0.3 on 2026-03-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='upi_id',
            field=models.CharField(blank=True, help_text="User's UPI ID for receiving payments", max_length=50),
        ),
    ]
