# Generated by Django 6.0.3 on 2026-03-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_recurringexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
