# Generated by Django 6.0.3 on 2026-03-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expense_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='converted_amount_inr',
            new_name='converted_amount',
        ),
        migrations.AddField(
            model_name='expensesplit',
            name='converted_share_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
